def getdate():
    import datetime
    return datetime.datetime.now()
print("Type s for sankalp")
print("Type r for rituraj")
print("Type a for aditya")
i = input()
if i=="s":
    print("you want to enter, edit or retrieve the data")
    print("type t to enter the data")
    print("type r to retrieve the data")
    print("type e to edit the data")
    io = input()
    if io=="t":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz = input()
        if ioz=="e":
            print("what do you want to write in it")
            wo = input()
            f = open("sankalpexersice.txt", "w")
            f.write(wo)
            f.close()
        elif ioz=="d":
            print("what do you want to write in it")
            wo1 = input()
            f1 = open("sankalpdiet.txt", "w")
            f1.write(wo1)
            f1.close()

    elif io=="r":
        print("what do you want to retrieve")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz1 = input()
        if ioz1=="e":
            f = open("sankalpexersice.txt")
            content = f.read()
            print(content)
            f.close()
        elif ioz1=="d":
            f1 = open("sankalpdiet.txt")
            content1 = f1.read()
            print(content1)
            f1.close()
        print(getdate())
    elif io=="e":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz9 = input()
        if ioz9=="e":
            print("what do you want to write ")
            f9 = open("sankalpexersice.txt", "a")
            wo9= input()
            f9.write("\n")
            f9.write(wo9)
            f9.close()
        elif ioz9=="d":
            print("what do you want to write ")
            f10 = open("sankalpdiet.txt", "a")
            wo10= input()
            f10.write("\n")
            f10.write(wo10)
            f10.close()
elif i=="r":
    print("you want to enter or retrieve the data")
    print("type t to enter the data")
    print("type r to retrieve the data")
    io1 = input()
    if io1=="t":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz1 = input()
        if ioz1=="e":
            print("what do you want to write in it")
            wo1 = input()
            f2 = open("riturajexersice.txt", "w")
            f2.write(wo1)
            f2.close()
        elif ioz1=="d":
            print("what do you want to write in it")
            wo2 = input()
            f3 = open("riturajdiet.txt", "w")
            f3.write(wo2)
            f3.close()
    elif io1=="r":
        print("what do you want to retrieve")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz1 = input()
        if ioz1=="e":
            f4 = open("riturajexersice.txt")
            content = f4.read()
            print(content)
            f4.close()
        elif ioz1=="d":
            f5 = open("riturajdiet.txt")
            content1 = f5.read()
            print(content1)
            f5.close()
        print(getdate())
    elif io1=="e":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz10 = input()
        if ioz10=="e":
            print("what do you want to write ")
            f11 = open("riturajexersice.txt", "a")
            wo11= input()
            f11.write("\n")
            f11.write(wo11)
            f11.close()
        elif ioz10=="d":
            print("what do you want to write ")
            f11 = open("riturajdiet.txt", "a")
            wo12= input()
            f11.write("\n")
            f11.write(wo12)
            f11.close()
if i=="a":
    print("you want to enter or retrieve the data")
    print("type t to enter the data")
    print("type r to retrieve the data")
    io2 = input()
    if io2=="t":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz2 = input()
        if ioz2=="e":
            print("what do you want to write in it")
            wo3 = input()
            f6 = open("adityaexersice.txt", "w")
            f6.write(wo3)
            f6.close()
        elif ioz2=="d":
            print("what do you want to write in it")
            wo4 = input()
            f7 = open("adityadiet.txt", "w")
            f7.write(wo4)
            f7.close()
    if io2=="r":
        print("what do you want to retrieve")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz2 = input()
        if ioz2=="e":
            f8 = open("adityaexersice.txt")
            content = f8.read()
            print(content)
            f8.close()
        elif ioz2=="d":
            f8 = open("adityadiet.txt")
            content1 = f8.read()
            print(content1)
            f8.close()
        print(getdate())
    elif io2=="e":
        print("where do you want to enter")
        print("Type e for exercise ")
        print("Type d for diet ")
        ioz19 = input()
        if ioz19=="e":
            print("what do you want to write ")
            f19 = open("adityaexersice.txt", "a")
            wo19= input()
            f19.write("\n")
            f19.write(wo19)
            f19.close()
        elif ioz19=="d":
            print("what do you want to write ")
            f18 = open("adityadiet.txt", "a")
            wo18= input()
            f18.write("\n")
            f18.write(wo18)
            f18.close()